using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace Platform.Infrastructure.Audit;

public sealed class AuditLogBootstrapHostedService(
    IServiceProvider services,
    ILogger<AuditLogBootstrapHostedService> logger) : IHostedService
{
    public async Task StartAsync(CancellationToken cancellationToken)
    {
        logger.LogInformation("Audit bootstrap started.");

        using var scope = services.CreateScope();
        var dbFactory = scope.ServiceProvider.GetRequiredService<IDbContextFactory<AuditLogDbContext>>();
        await using var db = await dbFactory.CreateDbContextAsync(cancellationToken);

        try
        {
            logger.LogInformation("Applying EF migrations for audit context.");
            await db.Database.MigrateAsync(cancellationToken);

            logger.LogInformation("Ensuring audit schema/table/indexes exist.");
            await db.Database.ExecuteSqlRawAsync("""
                CREATE SCHEMA IF NOT EXISTS audit;
                CREATE TABLE IF NOT EXISTS audit.admin_action_audit_logs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    occurred_at_utc TIMESTAMPTZ NOT NULL,
                    user_id VARCHAR(128) NOT NULL,
                    user_name VARCHAR(256) NULL,
                    role VARCHAR(64) NOT NULL,
                    action VARCHAR(256) NOT NULL,
                    http_method VARCHAR(16) NOT NULL,
                    request_path VARCHAR(512) NOT NULL,
                    query_string VARCHAR(1024) NULL,
                    response_status_code INTEGER NOT NULL,
                    correlation_id VARCHAR(128) NULL,
                    ip_address VARCHAR(128) NULL,
                    user_agent VARCHAR(1024) NULL
                );
                CREATE INDEX IF NOT EXISTS ix_admin_action_audit_logs_occurred_at_utc
                    ON audit.admin_action_audit_logs (occurred_at_utc);
                CREATE INDEX IF NOT EXISTS ix_admin_action_audit_logs_user_id
                    ON audit.admin_action_audit_logs (user_id);
                """, cancellationToken);

            logger.LogInformation("Audit bootstrap completed successfully.");
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Audit bootstrap failed.");
            throw;
        }
    }

    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
}
